baseURL: https://www.grahamnoblit.com
languageCode: en-us
title: Process
theme: "hugo-theme-cactus"
copyright: Graham Noblit
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts
      weight: 2
    # - name: Tags
    #   url: /tags
    #   weight: 3
    - name: About
      url: /about
      weight: 3
    - name: Papers
      url: /papers
      weight: 4
    - name: CV
      url: /files/CV.pdf
      weight: 5
    - name: RSS
      url:  https://www.grahamnoblit.com/index.xml
      weight: 6
markup:
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
params:
  colortheme: white
  comments:
    enabled: no
    engine: disqus
  dateFormat: '2006-01-02'
  description: I am a cultural evolutionist in the [Culture, Cognition, and Coevolution Lab](https://coevolution.fas.harvard.edu/) at Harvard University. I work to understand how political-economic institutions evolve across societies and how they impact minds and psychology. I ultimately hope to understand what our cultural origins imply for policy, politics, and even artificial intelligence.
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl:
  rss: yes
  show_updated: no
  showAllPostsOnHomePage: no
  showProjectsList: no
  showReadTime: no
  social:
    - link: https://github.com/gnoblit
      name: github
    - link: https://www.linkedin.com/in/graham-noblit/
      name: linkedin
    - link: graham_noblit@g.harvard.edu
      name: email
  tagsOverview: no
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
