---
title: Chartalism and War-Making
author: Graham Noblit
date: '2021-06-23'
slug: []
categories: []
tags: [chartalism, political evolution, cultural evolution, Ancient Rome, Ancient Greece, Athens, MMT]
draft: no
---

# Setting

Rarely in writing about markets do I see their origins explained. MMT and neochartalism serves an important role in describing the function of money, taxes, and markets. But the historian in me is drawn to a very specific question --- how, descriptively, did markets and money emerge? It's common to hear the complaint that a thing's origins need not constrain that thing's future uses or functions. This is certainly true, but it's also somewhat silly of a point to raise. Important information about an institution's function may be contained in its origins. For example, I have some work that suggests that lineages in China, which geographically vary quite a bit in their socio-political importance, successfully spread where risk pooling and access to land was of higher value. Does that mean lineages only serve that purpose or must serve that purpose? No --- history does not stand still. But we do learn about an important determinant of behavior, risk pooling; we learn something about that institutional environment, *i.e.* the context in which an institution emerged informing why and how it emerged; we learn about what institutional functions were demanded and lacking, and which may again be demanded should the institution sufficiently change or be withdrawn; etc. It is often useful and important to investigate and understand institutional origins. 

When it comes to markets and money, I often see information about origins missing. What is the story of markets emerging. Who pushed for them? Who did the legal and political work to support them? When and how did currency come into play? There's a huge coordination problem here. Nobody will be willing to accept money unless others already accept money. I rarely see this question acknowledged. A part of this is that such moments are rarely if ever documented. But it also seems that research on the topic is itself limited beyond Knapp, Simmel, Ingham, and Keynes. Instead, we are generally stuck with the barter story. Economies are really just barter, so the story goes. But if I raise cows and I want ducks then the person who raises ducks has to want cows or else I'm out of luck. So you invent money and markets so that you can exchange some token rather than the goods themselves. This is a story that works entirely at a functional level and is almost anti-institutionalist. 

Erica Schoenberger in "The Origins of the Market Economy: State Power, Territorial Control, and Modes of War Fighting" tells a different story which instead centralizes the state. She claims a weaker version of the following: without states pursuing their objectives then no markets would form. Interestingly, Schoenberger argues that states use markets to manage resources and space, and exchange is somewhat of a by-product. To evaluate this story, Schoenberger looks at three moments: 5th century BC Greece, Imperial Rome, and the Middle Ages from the 10^th^ - 13^th^ centuries. 

# Greece

Beginning with Greece, Schoenberger examines how coins became money and how exchange came to dominate social life. Coins, she says, move from being involved in political relations to economic ones (lubricating exchange). Alongside this process, Schoenberger says that goods which primarily circulated through gift-exchange and raiding (pillage) shift towards circulating through market exchange. Both transitions occur in the 5^th^ century BC as far as Athens is concerned.

## Coins

### Origins
Coins, importantly, are not about long-distance trade. Egyptians and Carthaginians, for instance, did most of their trade absent coinage (I do not know if this claim is true but it is Schoenberger's on pg 667, see note 10). Coins instead originally possessed political significance. But it was not states which introduced coins to Greece (coins antedate the presence of states). Instead, Schoenberger locates the political significance of coins among wealthy families competing among one another. Such families would mint coins as tokens of, and for the purpose of cementing, patron-client relations. As poleis emerged and grew, they aimed to curb the power of the landed aristocracy by minting their own coins. By doing this, the poleis essentially indicated that they were stepping in for and adopting the traditional roles of the landed elite (participation in religious ceremonies, donating gold objects to temples, etc.). Additionally, at this point in history, Greeks were largely autarchic (according to Morris' numbers, primary producers consumed 80% of output and no more than 1-2 % of output was transported beyond a few dozen miles from sites of production). Traders were viewed with contempt and trading was considered suitable behavior only for non-citizens. Both of these points indicates that markets were largely irrelevant. 

Schoenberger makes an interesting case with respect to the political and social nature of Greek society. Because of the intensive political and social networks that individuals were enmeshed in the logic of socially and politically alienating market-exchange was essentially anathema. Therefore, such exchange was reserved or seen as suitable only for individuals who did not exist in said networks --- non-citizens, foreigners, *metics*. I find this article both convincing but also I am somewhat skeptical of it. Chinese lineages often facilitated exchange and engaged intensively in production, sometimes benefiting from state monopolies. So social networks need not necessarily prevent intensive exchange. That being said, lineage members were also often excused from having to pay rents on lineage grounds and almost always benefited from rental rates far better than they could receive from the market, supporting Schoenberger's argument. Regardless, Schoenberger makes an important point here --- state entities did not introduce coinage with the idea of generating markets. This point is important because it allows us to avoid the start-up problem I mentioned before where coins have no exchange value unless they're already used for exchange. Schoenberger also points out that states were not consciously constructing markets at this point (unlike the colonial cases that Graeber and neochartalists rely on so much). 

## Transition

So how do coins come to adopt market roles, lubricating exchange? And how did exchange come to be so important for an autarchic society? Schoenberger points to two important forces at play --- democratization and imperialism. Aristocratic politics are first and foremost private and depend on relations between a patron (wealth) and a client (... not wealthy). Political exchange in such a case occurs in the patron's home (think of whose private space is assumed to be the site of a meeting be it in corporate and academic hierarchical spaces or 6^th^ century Athens). **Democratization** cannot permit such political relationships or at the very least needs to construct a more visible political arena that a broader slice of the population can participate in. This is how the *agora* was constructed --- a public and visible place where litigation, theater, and political exchange occurred.^[Bohannan and Dalton's *Markets in Africa* similarly emphasizes market spaces as often being sites where social, political, and informational activities occur far more often than commercial-exchange ones.] In the agora, one's actions became visible to the public body as a whole (allowing the construction of a public body, *ie* the formation of new and broader political coalitions on the basis of shared interests rather than hierarchical coalitions centered around a patron and his interests). Public pay for democratized activities like jury duty also expanded during this era. Other public/state roles similarly received salaries (Schoenberger points out Pericles' reference to Athens as a "salary-drawing city") and of course it is only possible to have a democratic state if the people who fill state-roles can derive a living from it.

This story is one that I think my colleagues in the Law and Political Economy movement would be very comfortable with. Money is used to construct a state. However, in doing so, Schoenberger points out that it requires the increased marketization of social life. Why? Well, if one is to receive coinage as pay then one must be able to spend it somewhere. Unfortunately, Schoenberger does not elaborate on this process but it is a book I would lov eto see written.

We then move on to **imperialism**. Athens of course is a notorious imperial power. Much of the public purse for instance was invested in the polis' standing navy. Athens' gigantic fleet required novel financial and political technologies whereas the historically previous style of small-scale wars did not. Two-hundred triremes and 40,000 rowers required "large-scale expenditures for construction, maintenance, wages, and provisions". Schoenberger argues that a shift in ideas or norms undergirded this changed behavior, one perhaps that politically engaged and frustrated MMTers could appreciate. In Pericles' oration just prior to the Peloponnesian War, Pericles argues that Athens "may need to spend *all* of its wealth in order to prevail". Power then is not achieved through accumulating and displaying wealth as one finds in Homer but by spending it. This is absolutely fascinating. The state, essentially, is discovering exchange --- the use of money to pursue its political objectives. This is *very* different from the use of wealth in Homer or small-scale societies whereby its main purpose is in display and donation. Instead, the state is essentialy constructing itself as an entity with objectives which acts, partially through exchange, to pursue those objectives. Schoenberger emphasizes here that the point of empire is not to get rich but rather to be powerful, to be glorious, and to be honorable.

I personally think that more should be made of this last point concerning a diversity of motivations. Even within our highly individualized and commodified society, it is difficult to argue that the wealthy pursue increasing their wealth so that they may further consume goods and services. Instead, wealth is a path to status and power and perhaps other social and psychological objectives. This psychological based reasoning would benefit from much more work. What people want to do with wealth will vary wildly across societies. It's also something that will change as we modify our economy and our politics Perhaps this appears to be "out there" but it is the topic of my own field, cultural evolution, which aims to understand cross-sectional and longitudinal psychological variation. 

## Conclusion

So what's of note? Well, interestingly, no taxes! Maybe taxes fit in here but there's no discussion of centralized sanctions by the state driving demand for money. We know colonial regimes have done that, so it's an available social technology, but as I've written elsewhere, it's a lot of foresight to ask from the earliest states. It's this unrealistic degree of foresight in the neochartalist story that has always bothered me. That being said, Schoenberger's story is entirely compatible with neochartalism and MMT --- the state uses money to construct its political vision.^[A point that JW Mason had to enlighten Harald Uhligh on, the previous co-editor of the Journal of Political Economy --- a top neoclassical journal: https://www.pairagraph.com/dialogue/bdbc4615eaad4a3c85e1e2cadf20f5a9.]

# Rome

So is MMT wrong? Are taxes irrelevant here in driving the evolution of money? Well, when we turn to Rome, it looks like taxes are extremely important in driving commercialization! Schoenberger discusses Keith Hopkins' argument that commodity trade in the Roman Empire was largely driven by taxes. Taxpayers had to convert their surplus to currency to satisfy the rather onerous taxation bill. How did they do this? Commercial sale. But wait, there's still a problem. Who would have the currency tokens to purchase these goods? A market needs both suppliers and buyers and a surplus of goods can only be purchased with a surplus of tokens. Here we see the point that I so rarely see discussed --- the role of the Roman soldier. Because of Rome's imperial (same as Athens!) ambitions, it invested heavily in its army and it paid them in the very tokens that others would require to pay their taxes. 

How did this all get off the ground? Well like Athens, Rome was transitioning from small-scale warfare whereby individuals provided their own food, arms, and armor to engaging warfare on a permanent and imperial basis. Soldiers could not work for part of the year on their farms and save up enough resources for their time at the front. Schoenberger argues that supply lines were unable to provide sufficient goods because they were so costly and that because soldiers were garrisoned that pillaging the country side was also not realistic. The solution was to "convert distant in-kind resources into money, which is much easier to move around over a huge territory, and to use that money to procure necessary inputs from regions closer to the frontiers". 

Note however, and Schoenberger does so, that the driving force here is militarization. Coming from an evolution of institutions angle, this point is subtly important. As states emerged, they did not intrinsically want resources. The earliest states had no conception of their "stateness" or their political potential. They did not and were not able to objectively or abstractly understand what strategies were available to them in their strategy set. They had to learn what they were capable of, what levers they could pull. Such learning largely occurred through experimentation and as a byproduct of other actions. Both Athens and Rome had imperial objectives and over time, but not initially,s large numbers of military personnel needed access to resources. Schoenberger's point is that it is under such conditions we should expect to see money and markets emerge. Otherwise, we should not expect to. 

# Conclusion

So it looks like there's some vindication for the neochartalist story from Schoenberger's perspective. Taxation does drive demand for currency and is a critical aspect for the growth of markets. However, interestingly, there seems to be a surprisingly **limited** use of state-spending, at least in the Roman case. There, state-spending did **not** finance state projects such as public buildings (temples, aqueducts), the corn dole, or even much of the army's provisioning. From a neochartalist perspective, we might consider this an inefficient use of political and economic technology. Perhaps there were institutional restrictions which did not permit such a jump in the use of spending or perhaps the use of physical coins meant that the political-economic institutions were essentially already doing all they could. 

I found this piece very satisfying. It is the first explication of the origins of money that I find to be coherent and satisfying. It is of course up to historians and classicists to determine whether it is correct or not.